#!/usr/bin/env python3
"""
Phase 9c: QAK Summary Note Generator
Reads qak.db and generates auto-updated QAK summary notes in the vault.

Summary notes are prefixed with "QAK — " and overwritten entirely each run.
"""

import sqlite3
from pathlib import Path
from datetime import datetime

DB_PATH = Path("/Users/giovanni.coppola/Library/CloudStorage/OneDrive-RegeneronPharmaceuticals,Inc/MyScripts/myGitHubRepos/QAK/qak.db")
VAULT = Path("/Users/giovanni.coppola/Library/CloudStorage/OneDrive-RegeneronPharmaceuticals,Inc/MyScripts/myGitHubRepos/gitVault/gitVault-notes")

NOW = datetime.now().strftime("%Y-%m-%d")
NOW_ISO = datetime.now().isoformat(timespec="seconds")
GENERATED_BY = "QAK builder v1.0"


def fmt(val, default="—"):
    """Format a value for table display."""
    if val is None or val == "" or val == "None":
        return default
    if isinstance(val, float) and val == int(val):
        return f"{int(val):,}"
    if isinstance(val, (int, float)):
        return f"{val:,}" if val >= 1000 else str(val)
    return str(val)


def link(name, prefix=""):
    """Create an Obsidian wiki-link."""
    if not name:
        return "—"
    return f"[[{prefix}{name}]]"


def frontmatter(source_query):
    """Generate YAML frontmatter for a summary note."""
    return f"""---
type: qak_summary
last_updated: "{NOW_ISO}"
source_query: "{source_query}"
generated_by: "{GENERATED_BY}"
tags:
  - qak-summary
  - auto-generated
---"""


def banner(title):
    """Generate the banner line."""
    return f"""\n# {title}\n> Auto-generated by QAK builder. Last updated: {NOW}. Do not edit manually.\n"""


def write_note(filename, content):
    """Write a summary note to the vault."""
    path = VAULT / filename
    path.write_text(content, encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Summary generators
# ---------------------------------------------------------------------------

def gen_disease_overview(conn):
    """QAK — Disease Overview.md"""
    rows = conn.execute("""
        SELECT d.id, d.name, d.n_patients_us, d.prevalence_per_100k,
               d.gwas_loci, d.gwas_largest_n
        FROM diseases d
        ORDER BY d.name
    """).fetchall()

    # Pre-compute counts
    gene_counts = dict(conn.execute("""
        SELECT disease_id, COUNT(*) FROM disease_gene GROUP BY disease_id
    """).fetchall())
    trial_counts = dict(conn.execute("""
        SELECT disease_id, COUNT(*) FROM disease_trial GROUP BY disease_id
    """).fetchall())
    paper_counts = dict(conn.execute("""
        SELECT disease_id, COUNT(*) FROM disease_paper GROUP BY disease_id
    """).fetchall())

    lines = [
        frontmatter("diseases overview"),
        banner("Disease Overview"),
        "| Disease | US Patients | Prevalence /100k | Genes | GWAS Loci | Papers | Trials |",
        "|---------|------------|------------------|-------|-----------|--------|--------|",
    ]

    for did, name, n_us, prev, gwas_loci, gwas_n in rows:
        lines.append(
            f"| {link(name)} | {fmt(n_us)} | {fmt(prev)} | "
            f"{gene_counts.get(did, 0)} | {fmt(gwas_loci)} | "
            f"{paper_counts.get(did, 0)} | {trial_counts.get(did, 0)} |"
        )

    lines.append(f"\n**{len(rows)} diseases** in database.\n")
    content = "\n".join(lines)
    write_note("QAK — Disease Overview.md", content)
    return "QAK — Disease Overview.md"


def gen_gene_overview(conn):
    """QAK — Gene Overview.md"""
    rows = conn.execute("""
        SELECT g.id, g.symbol, g.full_name, g.chromosome, g.protein_length
        FROM genes g
        ORDER BY g.symbol
    """).fetchall()

    disease_counts = dict(conn.execute("""
        SELECT gene_id, COUNT(*) FROM disease_gene GROUP BY gene_id
    """).fetchall())
    paper_counts = dict(conn.execute("""
        SELECT gene_id, COUNT(*) FROM gene_paper GROUP BY gene_id
    """).fetchall())
    strategy_counts = dict(conn.execute("""
        SELECT gene_id, COUNT(*) FROM strategy_gene GROUP BY gene_id
    """).fetchall())

    lines = [
        frontmatter("genes overview"),
        banner("Gene Overview"),
        "| Gene | Full Name | Chr | Length (aa) | Diseases | Papers | Strategies |",
        "|------|-----------|-----|-------------|----------|--------|------------|",
    ]

    for gid, symbol, full_name, chrom, prot_len in rows:
        lines.append(
            f"| {link(symbol, '^')} | {fmt(full_name)} | {fmt(chrom)} | {fmt(prot_len)} | "
            f"{disease_counts.get(gid, 0)} | {paper_counts.get(gid, 0)} | "
            f"{strategy_counts.get(gid, 0)} |"
        )

    lines.append(f"\n**{len(rows)} genes** in database.\n")
    content = "\n".join(lines)
    write_note("QAK — Gene Overview.md", content)
    return "QAK — Gene Overview.md"


def gen_trials_for_disease(conn, disease_id, disease_name):
    """QAK — Trials for <Disease>.md"""
    rows = conn.execute("""
        SELECT ct.trial_name, ct.drug, ct.phase, ct.n_enrolled,
               ct.outcome, ct.status, ct.primary_endpoint, ct.results_paper
        FROM clinical_trials ct
        JOIN disease_trial dt ON ct.id = dt.trial_id
        WHERE dt.disease_id = ?
        ORDER BY ct.phase, ct.trial_name
    """, (disease_id,)).fetchall()

    if not rows:
        return None

    safe_name = disease_name.replace("/", "-")
    filename = f"QAK — Trials for {safe_name}.md"

    lines = [
        frontmatter(f"clinical_trials WHERE disease = '{disease_name}'"),
        banner(f"Clinical Trials for {disease_name}"),
        "| Trial | Drug | Phase | N | Outcome | Status | Primary Endpoint |",
        "|-------|------|-------|---|---------|--------|------------------|",
    ]

    for tname, drug, phase, n_enr, outcome, status, endpoint, results in rows:
        results_link = f" {link(results, '@')}" if results else ""
        lines.append(
            f"| {link(tname)} | {fmt(drug)} | {fmt(phase)} | {fmt(n_enr)} | "
            f"{fmt(outcome)} | {fmt(status)} | {fmt(endpoint)}{results_link} |"
        )

    # Summary stats
    n_positive = sum(1 for r in rows if r[4] and "positive" in str(r[4]).lower())
    n_negative = sum(1 for r in rows if r[4] and "negative" in str(r[4]).lower())
    n_pending = len(rows) - n_positive - n_negative

    lines.append(f"\n**{len(rows)} trials** — {n_positive} positive, {n_negative} negative, {n_pending} pending/unknown.\n")
    content = "\n".join(lines)
    write_note(filename, content)
    return filename


def gen_trials_by_phase(conn):
    """QAK — Trials by Phase.md"""
    rows = conn.execute("""
        SELECT ct.trial_name, ct.drug, ct.phase, ct.outcome, ct.status,
               GROUP_CONCAT(d.name, ', ') as diseases
        FROM clinical_trials ct
        LEFT JOIN disease_trial dt ON ct.id = dt.trial_id
        LEFT JOIN diseases d ON d.id = dt.disease_id
        GROUP BY ct.id
        ORDER BY ct.phase, ct.trial_name
    """).fetchall()

    lines = [
        frontmatter("clinical_trials grouped by phase"),
        banner("Trials by Phase"),
        "| Trial | Drug | Phase | Disease(s) | Outcome | Status |",
        "|-------|------|-------|-----------|---------|--------|",
    ]

    for tname, drug, phase, outcome, status, diseases in rows:
        lines.append(
            f"| {link(tname)} | {fmt(drug)} | {fmt(phase)} | {fmt(diseases)} | "
            f"{fmt(outcome)} | {fmt(status)} |"
        )

    lines.append(f"\n**{len(rows)} trials** total.\n")
    content = "\n".join(lines)
    write_note("QAK — Trials by Phase.md", content)
    return "QAK — Trials by Phase.md"


def gen_trials_by_target(conn):
    """QAK — Trials by Target.md"""
    rows = conn.execute("""
        SELECT g.symbol, ct.trial_name, ct.drug, ct.phase, ct.outcome,
               GROUP_CONCAT(d.name, ', ') as diseases
        FROM trial_gene tg
        JOIN genes g ON g.id = tg.gene_id
        JOIN clinical_trials ct ON ct.id = tg.trial_id
        LEFT JOIN disease_trial dt ON ct.id = dt.trial_id
        LEFT JOIN diseases d ON d.id = dt.disease_id
        GROUP BY tg.trial_id, tg.gene_id
        ORDER BY g.symbol, ct.trial_name
    """).fetchall()

    lines = [
        frontmatter("clinical_trials grouped by target gene"),
        banner("Trials by Target Gene"),
        "| Gene | Trial | Drug | Phase | Disease(s) | Outcome |",
        "|------|-------|------|-------|-----------|---------|",
    ]

    for sym, tname, drug, phase, outcome, diseases in rows:
        lines.append(
            f"| {link(sym, '^')} | {link(tname)} | {fmt(drug)} | {fmt(phase)} | "
            f"{fmt(diseases)} | {fmt(outcome)} |"
        )

    lines.append(f"\n**{len(rows)} gene–trial links** total.\n")
    content = "\n".join(lines)
    write_note("QAK — Trials by Target.md", content)
    return "QAK — Trials by Target.md"


def gen_strategies_for_disease(conn, disease_id, disease_name):
    """QAK — Strategies for <Disease>.md"""
    rows = conn.execute("""
        SELECT ts.name, ts.modality,
               GROUP_CONCAT(DISTINCT g.symbol) as genes
        FROM therapeutic_strategies ts
        JOIN disease_strategy ds ON ts.id = ds.strategy_id
        LEFT JOIN strategy_gene sg ON ts.id = sg.strategy_id
        LEFT JOIN genes g ON g.id = sg.gene_id
        WHERE ds.disease_id = ?
        GROUP BY ts.id
        ORDER BY ts.name
    """, (disease_id,)).fetchall()

    if not rows:
        return None

    safe_name = disease_name.replace("/", "-")
    filename = f"QAK — Strategies for {safe_name}.md"

    lines = [
        frontmatter(f"therapeutic_strategies WHERE disease = '{disease_name}'"),
        banner(f"Therapeutic Strategies for {disease_name}"),
        "| Strategy | Modality | Target Genes |",
        "|----------|----------|--------------|",
    ]

    for sname, modality, genes in rows:
        gene_links = ", ".join(link(g.strip(), "^") for g in genes.split(",")) if genes else "—"
        lines.append(f"| {link(sname)} | {fmt(modality)} | {gene_links} |")

    lines.append(f"\n**{len(rows)} strategies** for {disease_name}.\n")
    content = "\n".join(lines)
    write_note(filename, content)
    return filename


def gen_papers_for_disease(conn, disease_id, disease_name):
    """QAK — Papers for <Disease>.md"""
    rows = conn.execute("""
        SELECT p.citekey, p.first_author, p.year, p.study_type,
               p.n_total, p.n_loci, p.obs_source
        FROM papers p
        JOIN disease_paper dp ON p.id = dp.paper_id
        WHERE dp.disease_id = ?
        ORDER BY p.year DESC, p.first_author
    """, (disease_id,)).fetchall()

    if not rows:
        return None

    safe_name = disease_name.replace("/", "-")
    filename = f"QAK — Papers for {safe_name}.md"

    lines = [
        frontmatter(f"papers WHERE disease = '{disease_name}'"),
        banner(f"Papers for {disease_name}"),
        "| Paper | Author | Year | Study Type | N | Loci | Summary |",
        "|-------|--------|------|-----------|---|------|---------|",
    ]

    for citekey, author, year, stype, n_total, n_loci, obs_src in rows:
        summary_flag = "human" if obs_src == "human" else ("ai" if obs_src == "ai" else "—")
        lines.append(
            f"| {link(citekey, '@')} | {fmt(author)} | {fmt(year)} | {fmt(stype)} | "
            f"{fmt(n_total)} | {fmt(n_loci)} | {summary_flag} |"
        )

    lines.append(f"\n**{len(rows)} papers** for {disease_name}.\n")
    content = "\n".join(lines)
    write_note(filename, content)
    return filename


def gen_failed_trials(conn):
    """QAK — Failed Trials.md"""
    rows = conn.execute("""
        SELECT ct.trial_name, ct.drug, ct.phase, ct.outcome,
               GROUP_CONCAT(DISTINCT d.name) as diseases,
               ct.results_paper
        FROM clinical_trials ct
        LEFT JOIN disease_trial dt ON ct.id = dt.trial_id
        LEFT JOIN diseases d ON d.id = dt.disease_id
        WHERE ct.outcome LIKE '%negative%'
        GROUP BY ct.id
        ORDER BY ct.trial_name
    """).fetchall()

    lines = [
        frontmatter("clinical_trials WHERE outcome = 'negative'"),
        banner("Failed Trials"),
        "| Trial | Drug | Phase | Disease(s) | Outcome | Results |",
        "|-------|------|-------|-----------|---------|---------|",
    ]

    for tname, drug, phase, outcome, diseases, results in rows:
        results_link = link(results, "@") if results else "—"
        lines.append(
            f"| {link(tname)} | {fmt(drug)} | {fmt(phase)} | {fmt(diseases)} | "
            f"{fmt(outcome)} | {results_link} |"
        )

    lines.append(f"\n**{len(rows)} trials** with negative outcome.\n")
    content = "\n".join(lines)
    write_note("QAK — Failed Trials.md", content)
    return "QAK — Failed Trials.md"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    conn = sqlite3.connect(str(DB_PATH))
    generated = []

    print("Generating QAK summary notes...\n")

    # Global summaries
    generated.append(gen_disease_overview(conn))
    generated.append(gen_gene_overview(conn))
    generated.append(gen_trials_by_phase(conn))
    generated.append(gen_trials_by_target(conn))
    generated.append(gen_failed_trials(conn))

    # Per-disease summaries (only for diseases with linked trials, papers, or strategies)
    diseases = conn.execute("SELECT id, name FROM diseases ORDER BY name").fetchall()
    for did, dname in diseases:
        f = gen_trials_for_disease(conn, did, dname)
        if f:
            generated.append(f)
        f = gen_strategies_for_disease(conn, did, dname)
        if f:
            generated.append(f)
        f = gen_papers_for_disease(conn, did, dname)
        if f:
            generated.append(f)

    conn.close()

    # Report
    print(f"Generated {len(generated)} summary notes:\n")
    for f in sorted(generated):
        print(f"  {f}")

    print(f"\nAll notes written to: {VAULT}")


if __name__ == "__main__":
    main()
